### ISSUE TITLE
beds not separated into mbr container in hierarchy view

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/sift#18] opened 2015-07-13 04:33 UTC
When beds are present in, for example a member in a formation, the beds plot at same rank as bed and are not nested.

e.g., https://dev.macrostrat.org/sift/info/?strat_id=13752

**Comment by jczaplew** [comment] 2015-10-29 16:11
@cambro  is this still an issue?

**Comment by cambro** [comment] 2015-12-16 15:27
I'm not sure here. the original link no longer works and I can't find that strat_name_id, which is odd....

**Comment by jczaplew** [comment] 2016-01-19 19:34
Closing this since it can't be confirmed.

**Closed by jczaplew** 2016-01-19 19:34 UTC
Labels: bug
